apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        loadBalancerIP: 192.168.1.220
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
