apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
    service:
      spec:
        loadBalancerIP: 192.168.1.220
    ports:
      web:
        port: 80
      websecure:
        port: 443
        tls:
          enabled: true
      traefik:
        port: 9000
        expose: true
        exposedPort: 9000
