---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBtyfHf/q16QHa1b5RknYf+rYwKIgqTE4NCcZiDTFkidnkFd8fx5plZ1ARmA2eO6hBFPvg9Ndt+mYp4S9ar1e1aqJhx1L4KyyRVZ6Z9KBq01P0Z2X8KRfpGh6vCPidghcsY9uZy6Nf+X3UGeqS3mlkw1H/YSMxTTA+3ZiEUazPsePq8PYVgzsf/pCxXBGH0+dir2zkdcWx+B00/TnKhIFZpJa1o1e8s1iq97hqvoxXiSILNOHKI4Ydx1Vh3cPEx/M7+It5KaVyDLKNDBO8SbJ9FqokE3ZKEuQ0qwa17yrOgwlGcUtFEFo0fCCXgWP9y8w5WYkemqN1Pk6FoVAyESFplaCTdz9QniPCgZ41ZvyaqWnbrI2pFpLO3KEcnXnx9/g5Vh/ubV+1h9PwW40BB/PfiU4u8G7uj0LpROBMdseEe7BfZ6IjqDepGO90yPzeuzqSymBEjkSVnQLoJpEmOh8UEEWifN2+AH0MmF5hT5lz8Ha3a6a/Tp6w2OKfOG4RbHivN4uKeZscHTP1BQ5MJMuKnAsVWeQ3Gh6IgQmtaNEqVqtF/YL6LQVUTHtMZUwDN9J0zzZ+XFilsE0Q/W7ll9FRjFQj5iDqtkt0uAAzeVAvqJ1Ii3Tr/Mx8BY/rD+1XbvntatRKvub1WEsyLyqGe/VAMeNb4cuRd5mt2F1tqdYN7EdXJQWjobwBS1LvVriDQKGe1JoJZvJzijdalw2hWIwtqxeLO0e3FYRx13NDPjJ61SNizDVZhttK4
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
