---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: example-secret
  namespace: default
spec:
  encryptedData:
    password: AgADTvnTo7AkUhoWtVso3AqVHoiORP7kQANmbiyL2Olj/B4HNLXTJyhrtjGR4vAdjRiXzNAiqJve+9xekB3vSmSx3TgDSFGf5nzTCROBo72Lmy66kjsBe2pz17oGf4VgGhVt76paVc3398AtunXIxjvpAKPMU3YmSexLz28rOuiQmDajd+nFR9kVz0lht4y2ACwWr2kResy+W//3GKVRSKnGHaFz6tVqdaoaZlDYHxXC3f3cAquXFmJV9aRzhj4n14qxymHUfrSs9bGiL6QauLeGU5xUSWN9BNnRNK8aX1bTLDEad6E+/r8E1qbfNVy6vKCqBuAlQI/uvb6SIE4h55VVB436bhDJRNAq0dJNAyqRhElRuszqCUY1P7z5dwrns1QgFyvT3I1oc6o2cGfnhIjjTrDGxJYVB2DWodMM4HwUUuq2cHuYkDO7P/8jMbxuok1EGMSMQ5MhKbfW9CFTYFVnIoiPVW/LQ40baWdkYbyG8L1jsRZ9Gq+7LPUdOAO2wu5KKnFES8vZoAanzAxHr6SCinic8zisDR///6sNOZS+u93Ke6CYZv/oZb4g1ufsQlUF6mDwg9bwBnNvTm1maa/fboDwBj4GM/zmoqRkMvpuUWHcH1gHk6kBAFQpCiAYEiy5Lm+1YlQy41bwBOuwI8uewyS5WJgIuSleVcMTtAPbCwAxS/n8QyU9BVPHXIg4Cdo4dNxSGc/0
    username: AgBHnXVKpgbETLUKN5NJbuWxdYZZKYjHNkMSlMyw6gnJWQ0AZ66Db21DqTqgPINZLOskvrrX3MQc3TyxQQt5PTw/6QVp8KcBiNxXF4EuevG9c1YqJDoMdWKm5urqVlZivvsndEKFik+R5ZD969+F+WXPA5C6LyGlGAwb79MX5ElwEol+E5+Ri/fLnhH10KvHf8wwO731a/rqnVyWJlJ6fJKrXjhNNxsOVecpBpx+tTt0niBKmi3G5a2v1jsjbhKYs8bP+e/gG5QcwJNEo9GoZZfNWPZcD8p8ndMl6w5b5EhLCKdGu6JurOHZpWhk7LL6GFFNPo6K4owOZu6Sx15lf+PJlVoMwWyGSnzctmf0/9WByPZ6YCdcMYVWhWqtE3PdnLLf0pN11ybjgLhn42onmYYfZmp1rERNBzXrk+6PLPBLAQA8mDxB3nbxMZ7Pkz/EUXPUBvOwtUpbN9vhVzsvbaHzxLAnsybBnvT31DUAxd6Iu5805h/rFhSCHkk8lQB/s4glAI8DSl7zuHjs+aVGSEF3Nb9aCMJEH+DxspK8DwW/6vxSBrVmXPwr9jIuS49xq1d7Jo6tSEs6GochDA//o5kLCc9sIFScPmlZCvan2qoiiGtsVg4Y8aHFyTKYOBaKAPci++6xVwOpHL+etZn+thV9EqJWO2Ip4NrrqSmeFZFJuLNUOXJnJXz+ZNpKNmcfcO2f2SP2
  template:
    metadata:
      creationTimestamp: null
      name: example-secret
      namespace: default
    type: Opaque
