---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-config-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgAPPQ+JfbHOQHA/NWnWyOCs5IZX1XzD6lKJ/nMVYPtqhrGnamkiUmdZ4TTEF9VOqSJIjqpx7+/nosAZqbDt54zxvfRIyJMT1LNcmLYvuXIEOLkYYZN7n/bvECL0+1CerYdNlsvitAPhGY+pwIzblun1aNC77NcsAHb3wouPkfFv5vEu/ySqNbYL9pUpsrBy2COPdAhfEEkwdB5j9VVeb3uFpc2I8P4+CUUkh7didkn9i2nl0xlt96+b7y9eLge24OPuo35RGxaxkLPbUGtxq7IoAzbPL15/ZvNSh9RmNUHFzzdlFt6Ci3dW9mVf3Gwg0z5m2caRQiU+8jUc972tqRTdTuo5oGMWQpL7ISQQXBWoaUsJxyQXRTXYo54Cg4I36FmJzGExLmw28LVSwPAalDt/6ApIm3g77XVE9BuQ4KHvYDswPPtx52h1HFyqvj1kISjozeQ9N24a7jTyn+HG3iGA9wRbUEUU6XOKrxeK0DwyEamHHAARgWSO6FDwK4P7UM8hvedQqswb5Jt/maL+dS69ca4lpqQ/XDDmrTjgwx3tC8uCsEk5fz11L8ZS1IzcfWnKael839hfl1LZ50690vhiD8IOVhG7SccD0l6MYILuYk62ZHUnA9lEEgelp9lC44VAz1DNOD+jnBELi89YABocevq/sOpiYIkIlnQ0R/Vub9pAsOY8acovLmpf/whidQAWweyAsNOyWoCsdH1EpSX3wYkQLcfFl5TabhPmQWQHQCqwx85EANCds2QXimvnRDxCRL184mp72XoNOxwu1N4IBmmBkTmQ5xoVSlXMaBzi1owQVziHD/QUy0hbPRd1BEnEZ+ePbOJBQ+M4Dnw+jY27g5GBVzotYV3QFjjIXXQoqb0C3KPAUri9ytXCW3gfzemFB2StzSVY/tBx0QioelL3Oog2UwlsDZRAoSFXm0kDCnHWo+JMwGapldkaqLr6dkkF1Rqnhfj8pIffvx0cYBD8cFRgXVIi9tOTDy3vyqxwYfvvI5WL0iOdrkuIVhHXORBnj56kTYC4uCcwf0rgl4SIv14svZXt+8UOfOe/LUeCkAjNl6I6PqtX9lDUd6Rbk382ZomT5ZsAvjy3CRbpVcgwl6WCMCMaw2baStiH8fQACwNyO43ABj57Ih8Ma95Gbss09ERG3+HIWO7QoptsnsHHMEPZIlGsDarlb/b9KbV9uldjZu4IIxg43gCB0PqZD1DyTVIgIqkn4t4FuFD3PT43dBmL9NesbQGab7Ly/VBg4vjTeUDHxwFQqdoq9o23gA==
  template:
    metadata:
      creationTimestamp: null
      name: traefik-config-values
      namespace: kube-system
    type: Opaque
